//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjetoPastelariaDoZe_2022.Properties {
    using System;
    
    
    /// <summary>
    ///   Uma classe de recurso de tipo de alta segurança, para pesquisar cadeias de caracteres localizadas etc.
    /// </summary>
    // Essa classe foi gerada automaticamente pela classe StronglyTypedResourceBuilder
    // através de uma ferramenta como ResGen ou Visual Studio.
    // Para adicionar ou remover um associado, edite o arquivo .ResX e execute ResGen novamente
    // com a opção /str, ou recrie o projeto do VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Retorna a instância de ResourceManager armazenada em cache usada por essa classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ProjetoPastelariaDoZe_2022.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Substitui a propriedade CurrentUICulture do thread atual para todas as
        ///   pesquisas de recursos que usam essa classe de recurso de tipo de alta segurança.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _35ac9cb2310afcc96b3938e16b3eb01f {
            get {
                object obj = ResourceManager.GetObject("35ac9cb2310afcc96b3938e16b3eb01f", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Continuar.
        /// </summary>
        internal static string button1Sair {
            get {
                return ResourceManager.GetString("button1Sair", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Sair.
        /// </summary>
        internal static string button2Sair {
            get {
                return ResourceManager.GetString("button2Sair", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Enviar para a bandeja.
        /// </summary>
        internal static string button3Sair {
            get {
                return ResourceManager.GetString("button3Sair", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Cadastro de Produtos.
        /// </summary>
        internal static string buttonCadEstoque {
            get {
                return ResourceManager.GetString("buttonCadEstoque", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Cliente.
        /// </summary>
        internal static string buttonCliEstoque {
            get {
                return ResourceManager.GetString("buttonCliEstoque", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Concluir.
        /// </summary>
        internal static string buttonConcluirCliente {
            get {
                return ResourceManager.GetString("buttonConcluirCliente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Concluir.
        /// </summary>
        internal static string buttonConcluirConfig {
            get {
                return ResourceManager.GetString("buttonConcluirConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Concluir.
        /// </summary>
        internal static string buttonConcluirFunc {
            get {
                return ResourceManager.GetString("buttonConcluirFunc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Concluir.
        /// </summary>
        internal static string buttonConcluirProd {
            get {
                return ResourceManager.GetString("buttonConcluirProd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Configurações.
        /// </summary>
        internal static string buttonConfigEstoque {
            get {
                return ResourceManager.GetString("buttonConfigEstoque", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Funcionário.
        /// </summary>
        internal static string buttonFuncEstoque {
            get {
                return ResourceManager.GetString("buttonFuncEstoque", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Acessar.
        /// </summary>
        internal static string buttonLogin {
            get {
                return ResourceManager.GetString("buttonLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Salvar.
        /// </summary>
        internal static string buttonSalvarConfig {
            get {
                return ResourceManager.GetString("buttonSalvarConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Voltar.
        /// </summary>
        internal static string buttonSobre {
            get {
                return ResourceManager.GetString("buttonSobre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Sobre.
        /// </summary>
        internal static string buttonSobreEstoque {
            get {
                return ResourceManager.GetString("buttonSobreEstoque", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Voltar.
        /// </summary>
        internal static string buttonVoltarCliente {
            get {
                return ResourceManager.GetString("buttonVoltarCliente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Voltar.
        /// </summary>
        internal static string buttonVoltarConfig {
            get {
                return ResourceManager.GetString("buttonVoltarConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Voltar.
        /// </summary>
        internal static string buttonVoltarFunc {
            get {
                return ResourceManager.GetString("buttonVoltarFunc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Voltar.
        /// </summary>
        internal static string buttonVoltarProd {
            get {
                return ResourceManager.GetString("buttonVoltarProd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a reiniciar e aplicar idioma..
        /// </summary>
        internal static string checkBoxIdioma {
            get {
                return ResourceManager.GetString("checkBoxIdioma", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap download {
            get {
                object obj = ResourceManager.GetObject("download", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap download1 {
            get {
                object obj = ResourceManager.GetObject("download1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a a.
        /// </summary>
        internal static string Funcionarios_FormClosing {
            get {
                return ResourceManager.GetString("Funcionarios_FormClosing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Descrição.
        /// </summary>
        internal static string groupBoxSobreDescricao {
            get {
                return ResourceManager.GetString("groupBoxSobreDescricao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a CPF.
        /// </summary>
        internal static string labelCpfCliente {
            get {
                return ResourceManager.GetString("labelCpfCliente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a CPF.
        /// </summary>
        internal static string labelCpfFuncionario {
            get {
                return ResourceManager.GetString("labelCpfFuncionario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Linguagem/Cultura.
        /// </summary>
        internal static string labelCulturaConfig {
            get {
                return ResourceManager.GetString("labelCulturaConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Descrição.
        /// </summary>
        internal static string labelDescricaoProdutos {
            get {
                return ResourceManager.GetString("labelDescricaoProdutos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Dia Fiado.
        /// </summary>
        internal static string labelDiaFiadoCliente {
            get {
                return ResourceManager.GetString("labelDiaFiadoCliente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a ID.
        /// </summary>
        internal static string labelidCliente {
            get {
                return ResourceManager.GetString("labelidCliente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a ID.
        /// </summary>
        internal static string labelidFuncionario {
            get {
                return ResourceManager.GetString("labelidFuncionario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a ID.
        /// </summary>
        internal static string labelidProdutos {
            get {
                return ResourceManager.GetString("labelidProdutos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Linguagem/Cultura.
        /// </summary>
        internal static string labelLinguagemConfig {
            get {
                return ResourceManager.GetString("labelLinguagemConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Fiado.
        /// </summary>
        internal static string labelMarcaFiadoCliente {
            get {
                return ResourceManager.GetString("labelMarcaFiadoCliente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Matricula.
        /// </summary>
        internal static string labelMatriculaFuncionario {
            get {
                return ResourceManager.GetString("labelMatriculaFuncionario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Multa/Atraso.
        /// </summary>
        internal static string labelMultaConfig {
            get {
                return ResourceManager.GetString("labelMultaConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Nome.
        /// </summary>
        internal static string labelNomeCliente {
            get {
                return ResourceManager.GetString("labelNomeCliente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Nome.
        /// </summary>
        internal static string labelNomeFuncionario {
            get {
                return ResourceManager.GetString("labelNomeFuncionario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Nome.
        /// </summary>
        internal static string labelNomeProdutos {
            get {
                return ResourceManager.GetString("labelNomeProdutos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Parâmetros.
        /// </summary>
        internal static string labelParametroConfig {
            get {
                return ResourceManager.GetString("labelParametroConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Percentual.
        /// </summary>
        internal static string labelPercentualConfig {
            get {
                return ResourceManager.GetString("labelPercentualConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Re-Senha.
        /// </summary>
        internal static string labelReSenhaCliente {
            get {
                return ResourceManager.GetString("labelReSenhaCliente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Re-Senha.
        /// </summary>
        internal static string labelReSenhaFuncionario {
            get {
                return ResourceManager.GetString("labelReSenhaFuncionario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Senha.
        /// </summary>
        internal static string labelSenhaCliente {
            get {
                return ResourceManager.GetString("labelSenhaCliente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Senha.
        /// </summary>
        internal static string labelSenhaFuncionario {
            get {
                return ResourceManager.GetString("labelSenhaFuncionario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Senha.
        /// </summary>
        internal static string labelSenhaLogin {
            get {
                return ResourceManager.GetString("labelSenhaLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Compainha.
        /// </summary>
        internal static string labelSobreCompanhia {
            get {
                return ResourceManager.GetString("labelSobreCompanhia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Copyright.
        /// </summary>
        internal static string labelSobreCopyright {
            get {
                return ResourceManager.GetString("labelSobreCopyright", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Nome.
        /// </summary>
        internal static string labelSobreNome {
            get {
                return ResourceManager.GetString("labelSobreNome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Versão.
        /// </summary>
        internal static string labelSobreVersao {
            get {
                return ResourceManager.GetString("labelSobreVersao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Telefone.
        /// </summary>
        internal static string labelTelefoneCliente {
            get {
                return ResourceManager.GetString("labelTelefoneCliente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Telefone.
        /// </summary>
        internal static string labelTelefoneFuncionario {
            get {
                return ResourceManager.GetString("labelTelefoneFuncionario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Configurações.
        /// </summary>
        internal static string labelTituloConfig {
            get {
                return ResourceManager.GetString("labelTituloConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a MENU GERAL.
        /// </summary>
        internal static string labelTituloEstoque {
            get {
                return ResourceManager.GetString("labelTituloEstoque", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Cadastro de Funcionários.
        /// </summary>
        internal static string labelTituloFuncionario {
            get {
                return ResourceManager.GetString("labelTituloFuncionario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a PASTELARIA.
        /// </summary>
        internal static string labelTituloLogin {
            get {
                return ResourceManager.GetString("labelTituloLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Cadastro de Produtos.
        /// </summary>
        internal static string labelTituloProdutos {
            get {
                return ResourceManager.GetString("labelTituloProdutos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Usuario.
        /// </summary>
        internal static string labelUsuarioLogin {
            get {
                return ResourceManager.GetString("labelUsuarioLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Valor.
        /// </summary>
        internal static string labelValorProdutos {
            get {
                return ResourceManager.GetString("labelValorProdutos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Deseja mesmo sair?.
        /// </summary>
        internal static string mng {
            get {
                return ResourceManager.GetString("mng", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Confirmação.
        /// </summary>
        internal static string mng2 {
            get {
                return ResourceManager.GetString("mng2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Admin.
        /// </summary>
        internal static string radioButtonAdm {
            get {
                return ResourceManager.GetString("radioButtonAdm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Balcão.
        /// </summary>
        internal static string radioButtonBalcao {
            get {
                return ResourceManager.GetString("radioButtonBalcao", resourceCulture);
            }
        }
    }
}
